const express = require('express')
const controller = require('../../controllers/customer/commerce.controller')
const { requireCustomer } = require('../../middleware/auth')

const router = express.Router()

router.get('/context', requireCustomer, controller.getCustomerContext)
router.get('/profile', requireCustomer, controller.getCustomerProfileFull)
router.get('/context/profile', requireCustomer, controller.getCustomerProfileFull)
router.get('/staff', requireCustomer, controller.getStaff)
router.get('/addresses', requireCustomer, controller.getAddresses)
router.post('/addresses', requireCustomer, controller.postAddress)
router.put('/addresses/:addressId', requireCustomer, controller.putAddress)
router.delete('/addresses/:addressId', requireCustomer, controller.deleteAddress)
router.post('/addresses/:addressId/default', requireCustomer, controller.postSetDefaultAddress)

router.get('/bookings', requireCustomer, controller.getBookings)
router.post('/bookings', requireCustomer, controller.postBooking)
router.post('/bookings/:bookingId/cancel', requireCustomer, controller.postCancelBooking)
router.post('/bookings/rating', requireCustomer, controller.postBookingRating)
router.post('/bookings/:bookingId/services/:bookingServiceId/rating', requireCustomer, controller.postBookingServiceRating)
router.get('/orders', requireCustomer, controller.getOrders)
router.post('/orders', requireCustomer, controller.postCeckout)
router.post('/orders/:orderId/reorder', requireCustomer, controller.postReorderOrder)
router.post('/orders/rating', requireCustomer, controller.postOrderRating)
router.post('/orders/:orderId/items/:orderItemId/rating', requireCustomer, controller.postOrderItemRating)
router.post('/orders/:orderId/cancel', requireCustomer, controller.postCancelOrder)
router.post('/orders/:orderId/complete', requireCustomer, controller.postCompleteOrder)
router.patch('/orders/:orderId/cancel', requireCustomer, controller.patchCancelOrder)
router.patch('/orders/:orderId/complete', requireCustomer, controller.patchCompleteOrder)

router.get('/cart', requireCustomer, controller.getCart)
router.post('/cart/items', requireCustomer, controller.postCartItem)
router.put('/cart/items/:cartItemId', requireCustomer, controller.putCartItem)
router.delete('/cart/items/:cartItemId', requireCustomer, controller.deleteCartItem)
router.delete('/cart/items', requireCustomer, controller.deleteCartItems)
router.post('/cart/checkout', requireCustomer, controller.postCeckout)

module.exports = router
