
const express = require('express')
const { promotionsPublicRoutes } = require('./promotions-public')

const { authRoutes } = require('./auth')
const { salonsRoutes } = require('./salons')
const { productsRoutes } = require('./products')
const { bookingsRoutes } = require('./bookings')
const { ordersRoutes } = require('./orders')
const { messagesRoutes } = require('./messages')
const { usersRoutes } = require('./users')
const { inventoryRoutes } = require('./inventory')
const { scheduleRoutes } = require('./schedule')
const { timeRoutes } = require('./time')
const { rolesRoutes } = require('./roles')
const { reviewsRoutes } = require('./reviews')
const { cartsRoutes } = require('./carts')
const { sessionsRoutes } = require('./sessions')
const { paymentsRoutes } = require('./payments')
const { notificationsRoutes } = require('./notifications')
const { giftCardsRoutes } = require('./giftcards')
const { promotionsRoutes } = require('./promotions')
const routes = express.Router()
routes.use('/promotions', promotionsPublicRoutes)
routes.use('/auth', authRoutes)
routes.use('/salons', salonsRoutes)
routes.use('/products', productsRoutes)
routes.use('/bookings', bookingsRoutes)
routes.use('/orders', ordersRoutes)
routes.use('/messages', messagesRoutes)
routes.use('/users', usersRoutes)
routes.use('/inventory', inventoryRoutes)
routes.use('/schedule', scheduleRoutes)
routes.use('/time', timeRoutes)
routes.use('/roles', rolesRoutes)
routes.use('/reviews', reviewsRoutes)
routes.use('/carts', cartsRoutes)
routes.use('/sessions', sessionsRoutes)
routes.use('/payments', paymentsRoutes)
routes.use('/notifications', notificationsRoutes)
routes.use('/gift-cards', giftCardsRoutes)
routes.use('/promotions', promotionsRoutes)

module.exports = { routes }
